openapi: 3.0.3
info:
  title: Base Map & Presence API
  version: 1.0.0
  description: >
    This API manages a shared base map layout (stored in MongoDB)
    and real-time presence tracking (stored in Redis) for workspaces —
    similar to Cosmos.video's spatial environment.

tags:
  - name: Map
    description: Base map initialization, retrieval, and layout management.
  - name: Presence
    description: Real-time workspace presence tracking via Redis.

paths:
  /maps/init:
    post:
      tags: [Map]
      summary: Initialize base map
      description: >
        Initializes a single base map using `data/baseMap.json` if one doesn't already exist.
      responses:
        "201":
          description: Base map created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MapResponse"
        "200":
          description: Base map already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MapResponse"
        "500":
          description: Server error

  /maps:
    get:
      tags: [Map]
      summary: Get the base map
      description: >
        Returns the current base map with dimensions, rooms, and objects.
      responses:
        "200":
          description: Base map details retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MapResponse"
        "404":
          description: Base map not found
        "500":
          description: Server error

    put:
      tags: [Map]
      summary: Update base map layout
      description: >
        Updates rooms, objects, or metadata for the base map.
        Intended for admin or map designer use.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rooms:
                  type: array
                  items:
                    $ref: "#/components/schemas/Room"
                objects:
                  type: array
                  items:
                    $ref: "#/components/schemas/MapObject"
                metadata:
                  type: object
                  additionalProperties: true
      responses:
        "200":
          description: Map updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MapResponse"
        "404":
          description: Base map not found
        "500":
          description: Server error

  /maps/{workspaceId}/presence:
    post:
      tags: [Presence]
      summary: Update user presence
      description: >
        Stores or updates a user's position, room, and metadata in Redis
        for a specific workspace.
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            example: "workspace-001"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId, x, y]
              properties:
                userId:
                  type: string
                  example: "user-123"
                x:
                  type: number
                  example: 1280
                y:
                  type: number
                  example: 720
                roomId:
                  type: string
                  example: "room-meeting"
                name:
                  type: string
                  example: "John Doe"
                avatarUrl:
                  type: string
                  example: "https://example.com/avatars/john.png"
      responses:
        "200":
          description: Presence updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  msg:
                    type: string
                    example: Presence updated
        "400":
          description: Missing workspaceId or userId
        "500":
          description: Server error

    get:
      tags: [Presence]
      summary: Get workspace presence
      description: >
        Fetches all active user presence data for a workspace from Redis.
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            example: "workspace-001"
      responses:
        "200":
          description: Presence list retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  presence:
                    type: array
                    items:
                      $ref: "#/components/schemas/Presence"
        "400":
          description: Invalid workspaceId
        "500":
          description: Server error

  /maps/{workspaceId}/presence/{userId}:
    delete:
      tags: [Presence]
      summary: Remove user presence
      description: >
        Deletes a user's presence record from Redis for a given workspace.
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            example: "workspace-001"
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user-123"
      responses:
        "200":
          description: User presence removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  msg:
                    type: string
                    example: User presence removed
        "400":
          description: Invalid parameters
        "500":
          description: Server error

components:
  schemas:
    MapResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        map:
          $ref: "#/components/schemas/Map"

    Map:
      type: object
      properties:
        _id:
          type: string
          example: "672a3fa95d2e0f30b43f42a1"
        name:
          type: string
          example: "Base Office Map"
        dimensions:
          type: object
          properties:
            width:
              type: number
              example: 3100
            height:
              type: number
              example: 2380
        rooms:
          type: array
          items:
            $ref: "#/components/schemas/Room"
        objects:
          type: array
          items:
            $ref: "#/components/schemas/MapObject"
        metadata:
          type: object
          additionalProperties: true
          example:
            initializedAt: "2025-11-09T06:00:00.000Z"

    Room:
      type: object
      properties:
        id:
          type: string
          example: "room-manager"
        name:
          type: string
          example: "Manager Cabin"
        area:
          type: object
          properties:
            x:
              type: number
              example: 2620
            y:
              type: number
              example: 212
            width:
              type: number
              example: 323
            height:
              type: number
              example: 240
        metadata:
          type: object
          example:
            capacity: 5

    MapObject:
      type: object
      properties:
        id:
          type: string
          example: "tableA"
        type:
          type: string
          example: "table"
        roomId:
          type: string
          example: "room-tableA"
        position:
          type: object
          properties:
            x:
              type: number
              example: 12.5
            y:
              type: number
              example: 21.5
        imageSize:
          type: number
          example: 450
        collision:
          type: object
          properties:
            width:
              type: number
              example: 300
            height:
              type: number
              example: 200
        metadata:
          type: object
          example:
            texture: "wood"

    Presence:
      type: object
      properties:
        userId:
          type: string
          example: "user-123"
        x:
          type: number
          example: 1280
        y:
          type: number
          example: 720
        roomId:
          type: string
          example: "room-meeting"
        name:
          type: string
          example: "John Doe"
        avatarUrl:
          type: string
          example: "https://example.com/avatar.png"
        updatedAt:
          type: integer
          example: 1736448123
