openapi: 3.0.3
info:
  title: Message API
  version: 1.0.0
  description: API documentation for sending, retrieving, and deleting messages in channels.

tags:
  - name: Message
    description: Manage messages in a workspace channel

paths:
  /messages:
    post:
      tags: [Message]
      summary: Send a message
      description: Create and send a new message in a specific channel.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - channelId
                - content
              properties:
                channelId:
                  type: string
                  description: ID of the channel to send the message in.
                  example: 671a2e9f12b3456a78c9d123
                content:
                  type: string
                  description: The text content of the message.
                  example: "Hey everyone, welcome to the project!"
                attachments:
                  type: array
                  description: Optional file attachments.
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                        example: "https://cdn.example.com/uploads/image.png"
                      filename:
                        type: string
                        example: "image.png"
      responses:
        201:
          description: Message created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        401:
          description: Unauthorized - Missing or invalid JWT token.
        500:
          description: Internal server error.

  /messages/channel/{channelId}:
    get:
      tags: [Message]
      summary: Get messages for a channel
      description: Retrieve all messages in a specific channel.
      security:
        - bearerAuth: []
      parameters:
        - name: channelId
          in: path
          required: true
          schema:
            type: string
          description: The channel ID whose messages you want to fetch.
      responses:
        200:
          description: A list of messages for the channel.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
        401:
          description: Unauthorized - Missing or invalid JWT token.
        500:
          description: Internal server error.

  /messages/message/{messageId}:
    delete:
      tags: [Message]
      summary: Delete a message
      description: Delete a specific message by its ID.
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the message to delete.
      responses:
        200:
          description: Message deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Message deleted successfully
                  data:
                    $ref: "#/components/schemas/Message"
        400:
          description: Missing messageId.
        404:
          description: Message not found.
        500:
          description: Internal server error.

components:
  schemas:
    Message:
      type: object
      properties:
        _id:
          type: string
          example: 671a2e9f12b3456a78c9d123
        channelId:
          type: string
          example: 671a2e9f12b3456a78c9d001
        sender:
          type: string
          example: 671a2e9f12b3456a78c9d002
        content:
          type: string
          example: "Hello team, please check the updated design!"
        attachments:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                example: "https://cdn.example.com/uploads/design.pdf"
              filename:
                type: string
                example: "design.pdf"
        createdAt:
          type: string
          format: date-time
          example: "2025-11-08T14:21:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-11-08T14:22:30Z"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
